### ISSUE TITLE
Retina icons

### ISSUE THREAD

**Issue by rubi0** [louischan/simplewhite#14]
Icons in retina display have a bad resolution. I don't know if it's only me, but can you tell me if this theme has retina icons? Thank you

**Comment by ununseptium** [comment]
yeah... please put high resolution icons in. This could be the first ff theme i ever going to use. So please just do it! :+1:

**Comment by alphachung** [comment]
+1.

**Comment by johngraciliano** [comment]
@louischan already made half pixel resulution (192 dpi) icons (maybe missing one or two) for the theme and they are in a branch of this project.  I am unclear why were they not brought into the main branch.  I am also unclear if using them really brings a significant benefit for the theme but I am limited by a 96 dpi (1 dot = 1 pixel) system.  Partially for being initially unaware of this, I am independently developing a set of icons in (resolution independent) `.svg` format  to implement them in my [version forked](https://github.com/johngraciliano/simplewhite) from this theme.  I already use `.svg` icons for the _Options_ and _Add-ons_ pages. Feedback on this matter and volunteers to test how the theme looks will be most welcome.
