### ISSUE TITLE
Should make about:preferences#search fit the lenth of search engine list

### ISSUE THREAD

**Issue by lychichem** [louischan/simplewhite#18]
![default](https://cloud.githubusercontent.com/assets/9316590/5641417/b25b4738-9673-11e4-829b-8f60b7cbd893.PNG)
If I have a search engine list long enough, then the UI will be like the image. It is not what users want. Hope to fix it.

**Comment by lychichem** [comment]
Use this code can fix this problem:
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

@-moz-document url("about:preferences#search") {
#engineList{height:auto !important;}
}

**Comment by louischan** [comment]
I have adopted the preferences.css from 36a2. I will fix the "add" button later. It is related to browser/searchbar.css
