### ISSUE TITLE
Share popup is too small

### ISSUE THREAD

**Issue by lychichem** [louischan/simplewhite#19]
As Firefox 35 and higher version added social API, which gives a share button to let users share page via social networks, we should fix it. Now it's too small for Weibo if you want to share something

**Comment by louischan** [comment]
Can you elaborate which button is too small? (Or is this problem resolved by now?)

**Comment by lychichem** [comment]
![default](https://cloud.githubusercontent.com/assets/9316590/6285999/9c32e6ae-b93d-11e4-9852-af6218c58466.PNG)
I mean this, the popup window is too small, I have to scroll.

**Comment by louischan** [comment]
e4c02198dbe6a8060f4ad3e389014c3d86064f60 sets `.social-share-frame { min-width: 756px; }`. It should have been fixed.
