### ISSUE TITLE
Toggle Tools not work properly on firefox nightly 38.0a1

### ISSUE THREAD

**Issue by lychichem** [louischan/simplewhite#20]
If simple white theme is activated, Toggle tool cannot show file type tabs.

**Comment by louischan** [comment]
What version of Firefox are you using?

**Comment by lychichem** [comment]
I use Firefox 38.0a1

发自我的 Windows Phone
________________________________
发件人: Louis Chan<mailto:notifications@github.com>
发送时间: ‎2015/‎1/‎16 0:56
收件人: louischan/simplewhite<mailto:simplewhite@noreply.github.com>
抄送: lychichem<mailto:leichixian@outlook.com>
主题: Re: [simplewhite] Toggle Tools not work properly on firefox nightly 38.0a1 (#20)

What version of Firefox are you using?

---

**Comment by lychichem** [comment]
![1](https://cloud.githubusercontent.com/assets/9316590/6286021/c5ade394-b93d-11e4-9f91-56bd8a2a8bce.PNG)
Seems your fix not work properly on Nightly 38.0a1 x64 edition(20150219) on windows. Here you are able to select data type if your theme is not activated.

**Comment by lychichem** [comment]
May I reopen this issue? It's actually not fixed.
