### ISSUE TITLE
Option to disable '3d' new tab page style

### ISSUE THREAD

**Issue by bwat47** [louischan/simplewhite#21]
I absolutely love this theme, hands down the most polished and usable firefox theme I've ever used :) However I personally really dislike the new 3d style new tab page that was introduced in an update. It would be really cool if there was an option for a flat style.

**Comment by louischan** [comment]
Thank you for the feedback :) It is possible to disable the 3D effect by applying the following CSS rule using userChrome.css or Stylish add-on.
```
@-moz-document url("about:newtab"){
  #newtab-grid {
    perspective: none;
  }
}
```
Enjoy!

**Comment by bwat47** [comment]
Thanks!
