### ISSUE TITLE
Layout issue under "about:preferences#search"

### ISSUE THREAD

**Issue by kjozwiak** [louischan/simplewhite#22]
There seems to be an issue with the layout under the "Search" preference when using the latest Nightly build.. Example:

![layoutissue](https://cloud.githubusercontent.com/assets/2602313/6023963/e089b392-ab95-11e4-9861-2e3b4b63d8e9.png)

Environment:

* Using OSX 10.10.2

STR:
* Download the latest m-c (Nightly) build: http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2015-02-02-03-02-32-mozilla-central/
* Download https://addons.mozilla.org/en-US/firefox/addon/simplewhite/
* Once installed, visit "about:preferences#search"

**Comment by lychichem** [comment]
fixed on  latest develop builds of these theme

**Comment by louischan** [comment]
Fix included in [v2.2b16](https://addons.mozilla.org/en-US/firefox/addon/simplewhite/versions/2.2b16). Thanks!
