### ISSUE TITLE
about: pages not styled correctly

### ISSUE THREAD

**Issue by PalmerAL** [louischan/simplewhite#23]
Just started using this theme - it looks great!

A few of the extension pages have no style at all with the theme installed, like this:

![screen shot 2015-02-12 at 7 56 10 pm](https://cloud.githubusercontent.com/assets/10314059/6180948/47d505f8-b2f1-11e4-8d04-faad21dce336.png)

**Comment by louischan** [comment]
Fixed in [v2.2b16](https://addons.mozilla.org/en-US/firefox/addon/simplewhite/versions/2.2b16) (reference: 59c6e8466767c4ad327c6febfce164f83402a74e). Thank you!
