### ISSUE TITLE
Context Menus need a border

### ISSUE THREAD

**Issue by imnes** [louischan/simplewhite#27]
For computer themes without a drop-shadow under popup menus, the context menus in this theme are hard to see.  Could be fixed by adding a small border if possible.  See attached screenshot.  

![simple-white-context-menus](https://cloud.githubusercontent.com/assets/3911628/6446099/3e65b98c-c0ce-11e4-8541-39357fe1f180.png)

**Comment by SW1FT** [comment]
Isn't this an issue related to Firefox itself and not this particular theme?

**Comment by imnes** [comment]
I don't know the standard theme looks fine with the classic windows theme.

**Comment by HotelCalifornia** [comment]
![m8](http://puu.sh/gW0UZ/dfe5c0d44b.png)
Weird, this is what I see

**Comment by imnes** [comment]
Looks like this computer also has effects (menu drop shadow, etc) disabled
for classic theme. You can close this issue, I'll turn shadows back on.

Thanks,
Nick
