### ISSUE TITLE
Mac FFx menu buttons too large.

### ISSUE THREAD

**Issue by JackCuthbert** [louischan/simplewhite#29]
The sync, customise, help, and quit buttons in the menu on Mac OS X are gigantic compared to other themes. [See image](http://i.imgur.com/XSHXHv2.png)

**Comment by louischan** [comment]
Could you try the latest beta version [v2.2b16](https://addons.mozilla.org/en-US/firefox/addon/simplewhite/versions/2.2b16)? I don't have a Retina Mac for testing. Let me know if the fix works.

**Comment by JackCuthbert** [comment]
That fixed it, cheers!

**Comment by louischan** [comment]
Great! Thanks.
