### ISSUE TITLE
about:config on Nightly looks broken

### ISSUE THREAD

**Issue by SW1FT** [louischan/simplewhite#31]
Also happens on Firefox Developer Edition (Aurora 38.0a2).
![aboutconfig nightly simplewhite](https://cloud.githubusercontent.com/assets/6627739/6946400/d7b9a3e2-d897-11e4-8f49-17f8ab3c498f.png)

**Comment by louischan** [comment]
Fixed in 81a45ff643c8d91e65a9345e5c95fb5758645e7d. Please try the latest [v2.2b16](https://addons.mozilla.org/en-US/firefox/addon/simplewhite/versions/2.2b16). Thank you!
