### ISSUE TITLE
Tabs size increase when Noise Control icon is present

### ISSUE THREAD

**Issue by SW1FT** [louischan/simplewhite#34]
I've been using an addon called [Noise Control](https://addons.mozilla.org/firefox/addon/noise-control/) which adds an icon on tabs that have HTML/Flash audio. When it detects audio and adds the icon it increases all tabs size which isn't intended and only happens with the Simple White theme enabled. This is very annoying because when you pause/unpause something that has audio on it, it will change the size of the tabs accordingly.

**Noise Control didn't detect audio:**
![noise control off](https://cloud.githubusercontent.com/assets/6627739/7094232/7b304ab4-dfb7-11e4-939c-5a488d8e7560.png)

**Noise Control detected audio:**
![noise control on](https://cloud.githubusercontent.com/assets/6627739/7094233/7b33467e-dfb7-11e4-9cc6-7227880b4c14.png)

As you can see, on the second image, the tabs are a bit taller.

**Comment by SW1FT** [comment]
I seem to have fixed this by making a style for Stylish with the following code: 
@-moz-document url("chrome://browser/content/browser.xul"){ #tabbrowser-tabs { height: 27px; } }

**Comment by louischan** [comment]
It can be fixed using:
```css
svg[anonid="noise-indicator"] {
  margin: 1px 0 -1px;
}
```

I'm not sure whether enforcing tab height is a good idea because this may affect users using a larger UI font. Default theme doesn't set the `height` attribute either.

**Comment by SW1FT** [comment]
I agree. As I'm not very familiar with CSS, I didn't know you could enforce height on a single svg.
