### ISSUE TITLE
Window Controls

### ISSUE THREAD

**Issue by meghprkh** [louischan/simplewhite#43]
How can I restore window controls to system theme but use Simple white? (For non windows users the window controls look odd)

**Comment by louischan** [comment]
The theme would not modify window controls in all platforms (unless in full-screen mode). Are you referring to window controls in full-screen mode?

**Comment by meghprkh** [comment]
I use an extension called HTitle on GNOME3(GTK3) Fedora 22 so that the titlebar and the tab bar are the same

**Comment by louischan** [comment]
It's an issue that should have been fixed a long time ago. Thanks for pointing it out!
