### ISSUE TITLE
Sync button problem.

### ISSUE THREAD

**Issue by ocvihoo** [louischan/simplewhite#55]
There is a problem with the Sync button. I let you see by yourself :

![capture d ecran 68](https://cloud.githubusercontent.com/assets/7969502/10589428/89fcfdcc-76ab-11e5-9b17-8f2fcd679dc7.png)

*Windows 10 - Firefox 41 - Connected to Firefox Sync.*

**Comment by johngraciliano** [comment]
I addressed this and other issues in [my fork](https://github.com/johngraciliano/simplewhite).  It needs yet to be reviewed by AMO but you are welcome to try it out.

**Comment by ocvihoo** [comment]
Thanks @johngraciliano. It works correctly with your fork.
