### ISSUE TITLE
Add Firefox Developer Editon support？

### ISSUE THREAD

**Issue by alim0x** [louischan/simplewhite#57]
Any plan to support Firefox Developer Editon? Development version is only support Firefox beta, current Firefox dev edtion is v44.0

**Comment by 3marcusw** [comment]
Check out [Simple White X](https://github.com/johngraciliano/simplewhite) which is actively developed

**Comment by alim0x** [comment]
@3marcusw thanks for your reply! Simple White X works perfectly :+1:
