### ISSUE TITLE
Tracking Protection Icon Not Shown on URL Bar

### ISSUE THREAD

**Issue by subnet142** [louischan/simplewhite#63]
I have my firefox (44.0.2) tracking protection enabled.  The tracking protection icon is not shown on the URL bar accordingly, although the function is good.  The theme is excellent overall as well.

**Comment by johngraciliano** [comment]
Try [Simple White X](https://addons.mozilla.org/en-US/firefox/addon/simplewhitex/) a [fork](https://github.com/johngraciliano/simplewhite) from this theme I keep updated.  The Options page is changed a lot, but that should not bother you. File an [issue](https://github.com/johngraciliano/simplewhite/issues) for me if needed.

**Comment by subnet142** [comment]
Wow, Simple White X works!  Many thanks.
